-- Oracle schema for Go Scheduler
-- Run this manually or via a migration tool
-- when using initialize-schema: never (the default).
--
-- To use a table prefix, replace "SCHEDULER_" with e.g. "MYAPP_SCHEDULER_"
-- and update the index names accordingly.

CREATE TABLE SCHEDULER_JOBS (
    JOB_ID         VARCHAR2(256) PRIMARY KEY,
    NAME           VARCHAR2(512) NOT NULL,
    TRIGGER_TYPE   VARCHAR2(32)  NOT NULL,
    TRIGGER_VALUE  VARCHAR2(512) NOT NULL,
    TIMEOUT_SECS   NUMBER DEFAULT 0 NOT NULL,
    NEXT_FIRE_TIME TIMESTAMP WITH TIME ZONE,
    STATE          VARCHAR2(32) DEFAULT 'WAITING' NOT NULL,
    INSTANCE_ID    VARCHAR2(256),
    ACQUIRED_AT    TIMESTAMP WITH TIME ZONE,
    CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_SCHED_JOBS_FIRE
    ON SCHEDULER_JOBS (NEXT_FIRE_TIME, STATE);