-- Oracle schema for Go Scheduler
-- Run this manually or via a migration tool (Liquibase, Flyway, etc.)
-- when using initialize-schema: never (the default).
--
-- To use a table prefix, replace "SCHEDULER_" with e.g. "MYAPP_SCHEDULER_"
-- and update the index names accordingly.

CREATE TABLE SCHEDULER_JOBS (
    JOB_ID         VARCHAR2(256) PRIMARY KEY,
    NAME           VARCHAR2(512) NOT NULL,
    TRIGGER_TYPE   VARCHAR2(32)  NOT NULL,
    TRIGGER_VALUE  VARCHAR2(512) NOT NULL,
    METADATA       CLOB DEFAULT '{}',
    NEXT_FIRE_TIME TIMESTAMP WITH TIME ZONE,
    STATE          VARCHAR2(32) DEFAULT 'WAITING' NOT NULL,
    INSTANCE_ID    VARCHAR2(256),
    ACQUIRED_AT    TIMESTAMP WITH TIME ZONE,
    ENABLED        NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_SCHED_JOBS_FIRE
    ON SCHEDULER_JOBS (NEXT_FIRE_TIME, STATE, ENABLED);

CREATE TABLE SCHEDULER_LOCKS (
    LOCK_NAME VARCHAR2(64) PRIMARY KEY
);

INSERT INTO SCHEDULER_LOCKS (LOCK_NAME)
    SELECT 'TRIGGER_ACCESS' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM SCHEDULER_LOCKS WHERE LOCK_NAME = 'TRIGGER_ACCESS');

INSERT INTO SCHEDULER_LOCKS (LOCK_NAME)
    SELECT 'STATE_ACCESS' FROM DUAL
    WHERE NOT EXISTS (SELECT 1 FROM SCHEDULER_LOCKS WHERE LOCK_NAME = 'STATE_ACCESS');

CREATE TABLE SCHEDULER_EXECUTIONS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_ID      VARCHAR2(256) NOT NULL,
    INSTANCE_ID VARCHAR2(256),
    STARTED_AT  TIMESTAMP WITH TIME ZONE NOT NULL,
    FINISHED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    ERROR       VARCHAR2(4000) DEFAULT ''
);

CREATE INDEX IDX_SCHED_EXEC_JOB
    ON SCHEDULER_EXECUTIONS (JOB_ID, STARTED_AT DESC);
