package jdbc

import (
	"fmt"
	"strings"
)

// Oracle implements Dialect for Oracle Database.
type Oracle struct{}

func (Oracle) Placeholder(index int) string { return fmt.Sprintf(":%d", index) }
func (Oracle) BooleanTrue() string          { return "1" }

func (Oracle) DateAddSQL(col, secondsExpr string) string {
	return fmt.Sprintf("%s + NUMTODSINTERVAL(%s, 'SECOND')", col, secondsExpr)
}

func (Oracle) SchemaSQL(prefix string) string {
	p := strings.ToUpper(prefix)
	return `
CREATE TABLE ` + p + `SCHEDULER_JOBS (
    JOB_ID         VARCHAR2(256) PRIMARY KEY,
    NAME           VARCHAR2(512) NOT NULL,
    TRIGGER_TYPE   VARCHAR2(32)  NOT NULL,
    TRIGGER_VALUE  VARCHAR2(512) NOT NULL,
    TIMEOUT_SECS   NUMBER        DEFAULT 0 NOT NULL,
    NEXT_FIRE_TIME TIMESTAMP WITH TIME ZONE,
    STATE          VARCHAR2(32)  DEFAULT 'WAITING' NOT NULL,
    INSTANCE_ID    VARCHAR2(256),
    ACQUIRED_AT    TIMESTAMP WITH TIME ZONE,
    ENABLED        NUMBER(1)     DEFAULT 1 NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_` + p + `SCHED_JOBS_FIRE
    ON ` + p + `SCHEDULER_JOBS (NEXT_FIRE_TIME, STATE, ENABLED);
`
}

func (Oracle) UpsertJobSQL(table string) string {
	return fmt.Sprintf(`
MERGE INTO %s DST
USING (
    SELECT :1 AS JOB_ID, :2 AS NAME, :3 AS TRIGGER_TYPE, :4 AS TRIGGER_VALUE,
           :5 AS TIMEOUT_SECS, :6 AS NEXT_FIRE_TIME, :7 AS STATE, :8 AS ENABLED,
           :9 AS CREATED_AT, :10 AS UPDATED_AT
    FROM DUAL
) SRC ON (DST.JOB_ID = SRC.JOB_ID)
WHEN MATCHED THEN UPDATE SET
    DST.NAME           = SRC.NAME,
    DST.TRIGGER_TYPE   = SRC.TRIGGER_TYPE,
    DST.TRIGGER_VALUE  = SRC.TRIGGER_VALUE,
    DST.TIMEOUT_SECS   = SRC.TIMEOUT_SECS,
    DST.NEXT_FIRE_TIME = SRC.NEXT_FIRE_TIME,
    DST.ENABLED        = SRC.ENABLED,
    DST.UPDATED_AT     = SRC.UPDATED_AT
WHEN NOT MATCHED THEN INSERT
    (JOB_ID, NAME, TRIGGER_TYPE, TRIGGER_VALUE, TIMEOUT_SECS,
     NEXT_FIRE_TIME, STATE, ENABLED, CREATED_AT, UPDATED_AT)
VALUES
    (SRC.JOB_ID, SRC.NAME, SRC.TRIGGER_TYPE, SRC.TRIGGER_VALUE,
     SRC.TIMEOUT_SECS, SRC.NEXT_FIRE_TIME, SRC.STATE, SRC.ENABLED,
     SRC.CREATED_AT, SRC.UPDATED_AT)
`, table)
}
